{
    "name": "inSitu Sales Connector",
    "summary": "Connect Odoo with field sales, DSD, inventory, and mobile invoicing",
    "version": "16.0.1.0.2",
    "category": "Sales/Sales",
    "author": "inSitu Sales",
    "website": "https://www.insitusales.com",
    "support": "info@insitusales.com",
    "license": "Other OSI approved licence",
    "depends": [
        "sale_management",
        "stock",
        "account",
    ],
    "data": [
        "security/insitu_security.xml",
        "security/ir.model.access.csv",
        "security/insitu_rules.xml",
        "data/ir_cron.xml",
        "views/connector_profile_views.xml",
        "views/sync_log_views.xml",
        "views/res_partner_views.xml",
        "views/product_product_views.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
        "views/stock_picking_views.xml",
        "views/insitu_menus.xml",
    ],
    "images": [
        "static/description/cover.png",
        "static/description/mobile-suite.png",
        "static/description/sync-map.png",
    ],
    "application": True,
    "installable": True,
}
